#ifndef TUTORIAL_IMGUI_GLOBALS_H
#define TUTORIAL_IMGUI_GLOBALS_H

#define TUTORIAL_IMGUI_AUTO_PLUGINNAME "AutoComboTutorialImGui"
#define TUTORIAL_IMGUI_AUTO_PLUGINDESC "An example automation plug-in for Adobe Photoshop that calls a filter plug-in utilizing ImGui."
#define TUTORIAL_IMGUI_AUTO_UUID "eaf75f91-e6f7-444b-a2fb-d0018ca572e5"
#define TUTORIAL_IMGUI_AUTO_RESOURCE_ID 18603
#define TUTORIAL_IMGUI_AUTO_SUITE_ID 'exaj'
#define TUTORIAL_IMGUI_AUTO_CLASS_ID TUTORIAL_IMGUI_AUTO_SUITE_ID
#define TUTORIAL_IMGUI_AUTO_EVENT_ID 'ExAn'
#define TUTORIAL_IMGUI_AUTO_VENDORNAME "memyselfandi"


#define TUTORIAL_IMGUI_FILTER_PLUGINNAME "FilterTutorialImGui"
#define TUTORIAL_IMGUI_FILTER_PLUGINDESC "A filter plug in for Adobe Photoshop that demonstrates usage of ImGui."
#define TUTORIAL_IMGUI_FILTER_UUID "27e54f31-7804-4237-96d6-d2d51083be43"
#define TUTORIAL_IMGUI_FILTER_RESOURCE_ID 18019
#define TUTORIAL_IMGUI_FILTER_SUITE_ID 'Filt'
#define TUTORIAL_IMGUI_FILTER_CLASS_ID TUTORIAL_IMGUI_FILTER_SUITE_ID
#define TUTORIAL_IMGUI_FILTER_EVENT_ID 'filt'
#define TUTORIAL_IMGUI_FILTER_VENDORNAME "memyselfandi"

#define TUTORIAL_IMGUI_FILTER_TRIGGERNAME "grigger"
#define TUTORIAL_IMGUI_FILTER_KEYTRIGGER 'Tgra'
#define TUTORIAL_IMGUI_FILTER_TYPETRIGGER 'TTgs'
#define TUTORIAL_IMGUI_FILTER_TRIGGERDESC "Activates the filter."

#define TUTORIAL_IMGUI_FILTER_KEYRESULT 'Rslu'
#define TUTORIAL_IMGUI_FILTER_TYPERESULT 'TRsm'

#define TUTORIAL_IMGUI_FILTER_ENUMINFONAME "Info"
#define TUTORIAL_IMGUI_FILTER_ENUMINFO 'Info'

#endif
